### ISSUE TITLE
Important question

### ISSUE THREAD

**Issue by CycloKid** [SuperTeamXP/Super-XP-Games#1]
how do you do the fnf html5 ports?
ive looked around youtube and google for answers but it only gives me videos on people playing them and not to port them.

**Comment by SubtleXP** [comment]
Well what you do is you get the source code, then you follow the instructions on the GitHub page with the source code on how to compile it and what you need, and since html5 is different from Windows and stuff, there's about a 99.99% chance you'll get an error that you will have to find out how to fix, and in order to test it after following the GitHub page instructions, type: lime test html5 and after a BUNCH of try's on getting it to work, (which sometimes depends on the mod) you'll have a working html5 port of the mod! Then all you have to do is type lime build html5 and go to where the game exported too

**Comment by CycloKid** [comment]
great. hopefully I could figure that out soon. maybe. probably..

**Comment by SubtleXP** [comment]
Good luck!
